### PR TITLE
Tiago Paim: lab-confidence-intervals

### PR DESCRIPTION
**Pull request by cleanspin**

### CODE REVIEW

**Comment by ta-data-lis** [comment]
Hey TIago, the files are incomplete, maybe a similar error than that of the other day.

**Comment by cleanspin** [comment]
-.-' i'm a terrible git user

**Comment by cleanspin** [comment]
wait, it's all there. just didn't do the bonus

**Comment by ta-data-lis** [comment]
Lab checked, good job!

All perfect! Quite sure that you can get back here and do the Bonus as well pretty quickly ;)

Keep up the good work!

**Pull request closed without merging**
